### ISSUE TITLE
DST-AST-UR-0030: (Semi-) automated Import

### ISSUE THREAD

**Issue by as-marcb** [STARIONGROUP/DEHP-ASTOS#3]
The ASTOS DST user would like to be supported during the import process by a (semi-) automated process for the recognition and mapping of relevant data.

Use Cases to cover:
- [ ] Launcher Design
- [ ] Coverage Analysis
- [ ] Eclipse Analysis
- [ ] Visibility Analysis
- [ ] Operational Lifetime Prediction analysis
- [ ] System Concept: Power

**Comment by as-svenw** [comment]
Realized by unit filtering and wizard
