### ISSUE TITLE
DST-AST-SR-0051: ASTOS Version Update Test

### ISSUE THREAD

**Issue by as-svenw** [STARIONGROUP/DEHP-ASTOS#31]
The ASTOS version converter shall make all required modifications in the scenario and the adapter settings.

**Comment by as-marcb** [comment]
Adapter settings fully retained on ASTOS version updates.
Regular version update approach can be applied to adapter settings, no changes to content since initial version.

**Comment by as-marcb** [comment]
Successful conversion 9.15→10.0
