### ISSUE TITLE
DST-GR-0110: local storage exchange data

### ISSUE THREAD

**Issue by as-svenw** [STARIONGROUP/DEHP-ASTOS#51]
The software shall store information about applied exchanges locally for review.

**Comment by as-marcb** [comment]
Each entry must at least contain required information:
DST-GUR-0102: Autor (Person at login)
DST-GUR-0103: Timestamp
DST-GUR-0104: Adapter version

**Comment by as-marcb** [comment]
Transfer log file in scenario folder is updated on each import/export.
A message for the respective Hub parameter ModelCode is generated. For scalar types, the value is saved as part of a message.
Adapter has UI to display entries (last to first).
