### ISSUE TITLE
DST-AST-UR-0060: Parameter Exchange Support

### ISSUE THREAD

**Issue by as-marcb** [STARIONGROUP/DEHP-ASTOS#6]
The user wants the tool (as a minimum) to support exchange of the following Annex A and B information between Hub and Matlab DST:
- Domain of Expertise
- Option
- ElementDefinition
- ElementUsage
- NestedElement
- all Parameters (and associated ActualFiniteStateLists) with values:
  - mass
  - mass margin
  - orbit arc
  - Keplerian orbit parameters
  - space trajectory element
  - epoch, coordinate system

**Comment by as-svenw** [comment]
Nested element is waived
