### ISSUE TITLE
DST-GR-0261: mark untestable code

### ISSUE THREAD

**Issue by as-svenw** [STARIONGROUP/DEHP-ASTOS#74]
The software shall have all "untestable" code marked clearly as such.

**Comment by as-svenw** [comment]
Untestable code marked but there is currently no means to let JaCoCo ignore such parts in the coverage analysis

**Comment by as-marcb** [comment]
Utilize class/source file filter to reduce to CDP4 scope.
Exclude UI code with `Generated` [annotation](https://github.com/jacoco/jacoco/pull/822).
